server:
  port: 8080
#  ssl:
#    key-store: src/main/resources/bootsecurity.p12
#    key-store-type: PKCS12
#    key-alias: ketstore
#    key-store-password: 123456

  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: root

  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
